##################################################################################################
# CSR Service
##################################################################################################
apiVersion: v1
kind: ServiceAccount
metadata:
  name: csrgo
---
apiVersion: v1
kind: Service
metadata:
  name: csrgo
  labels:
    app: csrgo
spec:
  ports:
  - port: 80
    name: http
  selector:
    app: csrgo
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: csrgo
spec:
  replicas: 0
  selector:
    matchLabels:
      app: csrgo
  template:
    metadata:
      labels:
        app: csrgo
    spec:
      serviceAccountName: csrgo
      containers:
      - name: csrgo
        image: csrgo
        command: ["/csrgo"]
        imagePullPolicy: IfNotPresent
---
